# Test 2024-06-25 at 20:32:09

name: Test

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Java - Hello World
      run:
        java HelloWorld.java

    - name: Java - Employee
      run:
        java Employee.java
